# -*- coding: utf-8 -*-
"""Coursera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114lqeRuaYYAI2Zqv-HoGXzSMz--Q_arc
"""

import pandas as pd

!pip install -q -U google-genai

from google.colab import userdata
from google import genai

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key = GEMINI_API_KEY)

print("Gemini configurado:", GEMINI_API_KEY is not None)

response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents="Responde solament: FUNCIONA"
)

print(response.text)

import pandas as pd
import numpy as np
import random
from datetime import timedelta
import re

# Asegúrate de que los nombres coincidan con los archivos que subiste
df_reviews = pd.read_csv('Coursera_reviews.csv')
df_faq = pd.read_csv('datafaq_enriched.csv')

df_reviews['date_reviews'] = pd.to_datetime(df_reviews['date_reviews'], errors='coerce')

#Las palabras exactas que pediste
keywords = [
    'data-science', 'datascience', 'machine', 'deep', 'neural', 'neuronal', r'\bml\b'
]
pattern = '|'.join(keywords)

#Filtramos usando SOLO lo que necesitamos
df_filtrado = df_reviews[df_reviews['course_id'].str.contains(pattern, case=False, na=False, regex=True)].copy()

# Limpiamos filas que estén vacías
df_filtrado = df_filtrado.dropna(subset=['reviews', 'rating'])

# Primero desordenamos todo un poco para que no queden solo reseñas de una misma fecha
df_filtrado = df_filtrado.sample(frac=1, random_state=1)

# Agrupamos por curso y tomamos solo las primeras 100 de cada grupo
df_filtrado = df_filtrado.groupby('course_id').head(100).reset_index(drop=True)

total_reviews_puras = len(df_filtrado)
cursos_unicos = df_filtrado['course_id'].nunique()

print(cursos_unicos)
print(total_reviews_puras)

# Mostrar la lista de los 30 cursos que sobrevivieron al filtro
cursos_finales = df_filtrado['course_id'].unique()

for i, curso in enumerate(cursos_finales, 1):
    print(f"{i}. {curso}")

# Agregamos las nuevas columnas para tu Motor Dinámico
df_filtrado['faq_answer'] = pd.NA  # Vacio para los alumnos reales
df_filtrado['is_faq'] = False      # Bandera en Falso

def limpiar_texto(texto):
    if not isinstance(texto, str): return ""
    texto = str(texto).lower()
    texto = re.sub(r'<.*?>', '', texto)
    texto = re.sub(r'[^\w\s]', '', texto)
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

# Aplicamos la limpieza a todas las reseñas de los alumnos
df_filtrado['reviews_clean'] = df_filtrado['reviews'].apply(limpiar_texto)

"""Data Harmonization
------
"""

RATIO = 20
faqs_necesarias = total_reviews_puras // RATIO

# Clonamos las FAQs hasta llegar a la meta
veces_a_repetir = int(np.ceil(faqs_necesarias / len(df_faq)))
df_faq_multiplicado = pd.concat([df_faq] * veces_a_repetir, ignore_index=True).head(faqs_necesarias)

# Inventamos variables realistas
nombres_base = ['Data Mentor', 'Course Assistant', 'AI Support', 'Prof. Ng', 'Data Scientist']
nombres_inventados = [random.choice(nombres_base) for _ in range(len(df_faq_multiplicado))]

fecha_min = df_filtrado['date_reviews'].min()
fecha_max = df_filtrado['date_reviews'].max()
dias_diferencia = (fecha_max - fecha_min).days
fechas_inventadas = [fecha_min + timedelta(days=random.randint(0, dias_diferencia)) for _ in range(len(df_faq_multiplicado))]

cursos_disponibles = df_filtrado['course_id'].dropna().unique()
cursos_inventados = [random.choice(cursos_disponibles) for _ in range(len(df_faq_multiplicado))]

# Armamos el DataFrame de FAQs con las COLUMNAS SEPARADAS
df_faq_adaptado = pd.DataFrame({
    'reviews': df_faq_multiplicado['Question'],    # SOLO LA PREGUNTA
    'faq_answer': df_faq_multiplicado['Answer'],   # SOLO LA RESPUESTA
    'is_faq': True,                                # BANDERA VERDADERA
    'reviewers': nombres_inventados,
    'date_reviews': fechas_inventadas,
    'rating': 5,
    'course_id': cursos_inventados,
    'reviews_clean': df_faq_multiplicado['Question'].apply(limpiar_texto)
})

print(faqs_necesarias)

from google.colab import files

# Juntamos ambos mundos
df_maestro = pd.concat([df_filtrado, df_faq_adaptado], ignore_index=True)

# Shuffle (mezclamos aleatoriamente)
df_maestro = df_maestro.sample(frac=1, random_state=42).reset_index(drop=True)

# Guardamos el archivo
nombre_final = 'Database_Motor_DataScience_Puro.csv'
df_maestro.to_csv(nombre_final, index=False)
print(total_reviews_puras)
print(faqs_necesarias)
print(len(df_maestro))

# Descargamos el archivo a tu PC
files.download(nombre_final)

# Mostramos un pequeño vistazo de cómo quedó
display(df_maestro.head())

"""analisis de sentimientos
===
"""

from google import genai
from google.colab import userdata
from tqdm import tqdm
import time

GEMINI_API_KEY = "AIzaSyCCROrXqsCb5nPEHztur2CWmLAyzK6KZHg"
client = genai.Client(api_key=GEMINI_API_KEY)

PROMPT_BASE = """
Eres un experto analizando sentimientos de estudiantes.
Clasifica la siguiente reseña usando ÚNICAMENTE una de estas tres palabras: Positivo, Negativo o Neutral.
No agregues puntos, ni explicaciones, ni comillas. Solo la palabra.

Reseña a analizar:
"""

def analizar_con_gemini(fila):
    if fila['is_faq'] == True:
        return "FAQ Educativo"

    texto = str(fila['reviews'])
    if not texto.strip():
        return "Neutral"

    # Cortamos a 2000 caracteres para ahorrar tokens y tiempo
    texto = texto[:2000]

    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash", # Usamos la versión oficial actual
            contents=PROMPT_BASE + texto
        )

        # Limpiamos la respuesta por si Gemini le puso espacios o saltos de línea
        sentimiento = response.text.strip().capitalize()

        # Validamos que solo sea una de las opciones permitidas
        if sentimiento in ["Positivo", "Negativo", "Neutral"]:
            return sentimiento
        else:
            return "Neutral (Error API)"

    except Exception as e:
        # Si Google nos bloquea por límite de cuota (Rate Limit), esperamos unos segundos
        if "429" in str(e) or "quota" in str(e).lower():
            time.sleep(10) # Pausa de 10 segundos
        print(f"Error detectado: {e}")
        return "Neutral (Error API)"

# Agregamos una pequeña pausa entre filas para no saturar la API
tqdm.pandas(desc="Gemini Analizando")
df_maestro['sentiment'] = df_maestro.progress_apply(
    lambda fila: time.sleep(4.1) or analizar_con_gemini(fila), axis=1
)

nombre_final = 'Database_Motor_Final_Gemini.csv'
df_maestro.to_csv(nombre_final, index=False)

from google.colab import files
files.download(nombre_final)

print(df_maestro['sentiment'].value_counts())

"""analisis de sentimientos con XLM-RoBERTa
=======
"""

from transformers import pipeline
import pandas as pd
from tqdm import tqdm

# Este modelo es el estándar actual para datasets con varios idiomas
analyzer_multi = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    tokenizer="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    device=0 # Usa la GPU de Colab
)

def analizar_sentimiento_local(fila):
    if fila['is_faq'] == True:
        return "FAQ Educativo"

    texto = str(fila['reviews'])
    if not texto.strip():
        return "Neutral"

    try:
        resultado = analyzer_multi(texto, truncation=True, max_length=512)[0]
        label = resultado['label']

        if label == 'LABEL_0' or label == 'negative': return "Negativo"
        elif label == 'LABEL_1' or label == 'neutral': return "Neutral"
        elif label == 'LABEL_2' or label == 'positive': return "Positivo"
        else: return "Neutral"

    except Exception as e:
        return "Neutral"

# Usamos la barra de progreso (esta vez irá rapidísimo)
tqdm.pandas(desc="Procesando reseñas")
df_maestro['sentiment'] = df_maestro.progress_apply(analizar_sentimiento_local, axis=1)

nombre_final_sentimientos = 'Database_Motor_Final_Completada.csv'
df_maestro.to_csv(nombre_final_sentimientos, index=False)

from google.colab import files
files.download(nombre_final_sentimientos)

print(df_maestro['sentiment'].value_counts())